version: '3.2'
services:
  nextjs_prisma:
    container_name: nextjs_prisma
    # ホスト名を明示的に指定する
    hostname: localhost
    build:
      context: .
      dockerfile: ./ubuntu/Dockerfile
      args:
        USER_ID: 1000
        USER_NAME: vscode
        GROUP_ID: 1000
        GROUP_NAME: vscode
        WORK_DIR: develop
    env_file: devcontainer.env
    environment:
      - TZ=JST-9
    ports:
      - 80:80
      - 3000:3000
    volumes:
      # ソースコードとdevcontainerを一緒に管理する場合は明示的にマウント先を指定
      - ..:/home/vscode/develop:cached
      - ~/.ssh:/home/vscode/.ssh
    command: sleep infinity
